### ISSUE TITLE
'non-unique multi-index' error when calling pd.concat on bim_table and reference_genome_data

### ISSUE THREAD

**Issue by mr664** [endrebak/snpflip#10]
I'm attempting to check for strand flips between my human dataset and the human reference fasta (human_g1k_v37.fa). For this I've changed the chromosome names in the reference to >chr<num> and removed non-autosomal chromosomes.

The error listed below appears to occur when attempting to concatenate the bim_table and reference_genome_data.

```
Traceback (most recent call last):
  File "/home/matt/anaconda3/bin/snpflip", line 42, in <module>
    snp_table = create_snp_table(args["--bim-file"], args["--fasta-genome"])
  File "/home/matt/anaconda3/lib/python3.4/site-packages/snp_flip/table.py", line 13, in create_snp_table
    snp_table = pd.concat([bim_table, reference_genome_data], axis=1)
  File "/home/matt/anaconda3/lib/python3.4/site-packages/pandas/tools/merge.py", line 810, in concat
    return op.get_result()
  File "/home/matt/anaconda3/lib/python3.4/site-packages/pandas/tools/merge.py", line 987, in get_result
    indexers[ax] = obj_labels.reindex(new_labels)[1]
  File "/home/matt/anaconda3/lib/python3.4/site-packages/pandas/core/index.py", line 5159, in reindex
    "cannot handle a non-unique multi-index!")
Exception: cannot handle a non-unique multi-index!
```

**Comment by endrebak** [comment]
This is more of a pandas issue though? I think pandas is complaining that you cannot concatenate two dfs that contain the same index entries.

Anyways, if you could tell me what you'd like to achieve it would be easier for me to help you. Do you want to print the reference genome data?

**Comment by mr664** [comment]
Here's the top of both the bim_table and reference_genome_data:

>>> bim_table.head()
	chromosome	position	snp_name	genetic_distance	allele_1	allele_2
0	1	752565	rs3094315,rs3094315-131_B_F_1865134815	0	T	C
1	1	752720	rs3131972,rs3131972-131_T_R_1857421833	0	G	A
2	1	754062	kgp6703048,kgp6703048-0_T_R_1817782034	0	A	C
3	1	761763	kgp15286661,kgp15286661-0_B_R_1836182266	0	T	C
4	1	767676	kgp3393353,kgp3393353-0_T_F_1821472192	0	A	G
5	1	770917	kgp4076808,kgp4076808-0_T_R_1817946169	0	A	C
6	1	774046	kgp15275285,kgp15275285-0_T_F_1836115694	0	A	G
7	1	779321	kgp5225889,kgp5225889-0_T_F_1821209299	0	G	A
8	1	783303	kgp12142302,kgp12142302-0_B_F_1821462394	0	T	C




>>> reference_genome_data.head()
                    reference reference_rev
chromosome position                        
2          15671            A             T
           28864            G             C
           29442            T             A
           31790            C             G
           33432            C             G

**Comment by endrebak** [comment]
One of the output files has the extension `.annotated_bim`. It contains data from the reference genome used in the column called `reference`.

If you want to compare the two genomes, snpflip really isn't meant for that*, although it is possible with the output files created. But the best way would probably be to use pyfaidx https://github.com/mdshw5/pyfaidx to look up SNPs in the two reference genomes and then compare them.

 If you want to use snpflip, try running it once per reference genome (yours and the official) and then `merge` the two `annotated_bim` files.

*Unless you have a bim file from your reference genome- then it is straightforward.

**Comment by endrebak** [comment]
Ehm, I think I might have misunderstood your issue.

If you could post a link to the genome you are using, I'll try to fix this.

**Comment by endrebak** [comment]
Is this your genome?: 

http://ftp-trace.ncbi.nih.gov/1000genomes/ftp/technical/reference/human_g1k_v37.fasta.gz

I'll play around with it tonight and see if I can reproduce the error. If not, I might need your bim file to debug this, if you'll allow it  (it does not contain confidential/private information - all that is in the bed files).

**Comment by mr664** [comment]
Yeah, that gz should contain the correct reference genome. Though keep in mine that I changed, with sed, the headers to '>chr1', '>chr2' etc. I also removed non-autosomes (so X, Y & psuedoautonomous).

What's your preferred email address? I'll send the bim you to via that.

**Comment by endrebak** [comment]
Endrebak85@gmail.com

Thanks.

**Comment by endrebak** [comment]
I get a fasta indexing error from pyfaidx when I try to use that genome. Can you try http://hgdownload.cse.ucsc.edu/goldenpath/hg19/bigZips/ until I get it working? `chromFa.tar.gz` should contain the genome you want (you need to concat the files yourself).

**Comment by endrebak** [comment]
Error I experienced reported at: https://github.com/mdshw5/pyfaidx/issues/83

**Comment by mr664** [comment]
That error didn't occur with my input because I removed the non-autosomes (X, Y, XY, MT etc.) from the reference genome fasta, leaving only chromosomes 1 to 22 in the file.

Instead snpflip breaks after parsing in the bim and reference fasta, when trying to create the 'snp_table' variable in table.py: ```snp_table = pd.concat([bim_table, reference_genome_data], axis=1)```

**Comment by endrebak** [comment]
I'll look into that further tonight, sorry for the delay (reproducing errors can be tricky).

**Comment by endrebak** [comment]
I think I got it working now. Would you mind trying 

`pip install snpflip==0.0.4`?

**Comment by mr664** [comment]
Everything seems to be working now, thanks for your help!

**Comment by endrebak** [comment]
Closing this, thanks for reporting.

Ps. updated the docs. You did not have to rename the chromosomes in the fasta files if they are of the type

`>chr1<WHITESPACE>any text here` or  `>1<WHITESPACE>any text here`. I.e. has the correct chromosome name and then whitespace and then whatever.
