### ISSUE TITLE
error: string index out of range

### ISSUE THREAD

**Issue by laurenleesc** [endrebak/snpflip#11]
Hi,

I am using the reference genome build:

 ftp://ftp.ncbi.nlm.nih.gov/genomes/archive/old_genbank/Eukaryotes/vertebrates_mammals/Homo_sapiens/GRCh37/special_requests/

but am getting the following error, below:
-------------------------------------------------------------------
C:\Python27\Scripts>python snpflip --bim-file=dbGaP_Genotypes_Breast_c3.bim --fasta-genome=GRCh37-lite.fa
Chromosome 23 in .bim, but not in fasta file.
Chromosome 26 in .bim, but not in fasta file.
There were 69 'N' nucleotides in chromosome 20.
There were 62 'N' nucleotides in chromosome 21.
There were 198 'N' nucleotides in chromosome 22.
There were 253 'N' nucleotides in chromosome 1.
Traceback (most recent call last):
  File "snpflip", line 42, in <module>
    snp_table = create_snp_table(args["--bim-file"], args["--fasta-genome"])
  File "C:\Python27\lib\site-packages\snp_flip\table.py", line 11, in create_snp_table
    reference_genome_data = get_reference_genome_data(bim_table, fa_file)
  File "C:\Python27\lib\site-packages\snp_flip\reference_genome.py", line 31, in get_reference_genome_data
    snp_nucleotides = [snp.upper() for snp in _get_snps(str(nucleotides))]
IndexError: string index out of range
--------------------------------------------------------------------

Any advice?  Thanks!

**Comment by endrebak** [comment]
See #12. Thanks for reporting this.
