### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by delgrodel** [endrebak/snpflip#7]
First of all, thank you for the tremendous amount of effort you've put into this program.

When I attempt to run the script (v0.0.2) using a UCSC hg19 reference genome I concatenated, I receive the following error:

```
snpflip --bim-file=../examples/example.bim --fasta-genome=ucsc_19_ref_gen.fa --output-prefix=example_output
Chromosome 25 in .bim, but not in fasta file.
There were 3 'N' nucleotides in chromosome1.
There were 1 'N' nucleotides in chromosomeY.
There were 2 'N' nucleotides in chromosome2.
Traceback (most recent call last):
  File "./snpflip", line 42, in <module>
    snp_table = create_snp_table(args["--bim-file"], args["--fasta-genome"])
  File "/home/usr/.local/lib/python2.7/site-packages/snp_flip/table.py", line 11, in create_snp_table
    reference_genome_data = get_reference_genome_data(bim_table, fa_file)
  File "/home/usr/.local/lib/python2.7/site-packages/snp_flip/reference_genome.py", line 38, in get_reference_genome_data
    lambda n: {"A": "T",
  File "/home/usr/.local/lib/python2.7/site-packages/pandas/core/series.py", line 2160, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/src/inference.pyx", line 1059, in pandas.lib.map_infer (pandas/lib.c:62187)
  File "/home/usr/.local/lib/python2.7/site-packages/snp_flip/reference_genome.py", line 41, in <lambda>
    "G": "C"}[n])
KeyError: 'N'
```

Here is the output from `grep -n '>' ucsc_19_ref_gen.fa`:
```
1:>chr1
4985015:>chr2
9849004:>chr3
13809454:>chr4
17632541:>chr5
21250848:>chr6
24673151:>chr7
27855926:>chr8
30783208:>chr9
33607478:>chr10
36318174:>chr11
39018306:>chr12
41695345:>chr13
43998744:>chr14
46145736:>chr15
48196365:>chr16
50003462:>chr17
51627368:>chr18
53188914:>chr19
54371495:>chr20
55632007:>chr21
56594606:>chr22
57620699:>chrX
60726112:>chrY
61913585:>chrM
```

The .bim file is the example.bim supplied with the snpflip package.  Aside from the UCSC reference genome, I've also tried the 1kGP version from [here] (http://ftp-trace.ncbi.nih.gov/1000genomes/ftp/technical/reference/) and received the same error. However, the script successfully executes when using the supplied example.fa.

I really don't know what to make of this.  Your help is greatly appreciated!

**Comment by delgrodel** [comment]
Interestingly, the problem appears to be fixed if the .bim file is broken by chromosome.

**Comment by endrebak** [comment]
Thanks for the error report. (It wasn't a lot of work, btw, only 110 lines of Python.) 

What the error message says is that it cannot find the "nucleotide mate" (I forget the term) for N (like C has G and A has T). This means that some of the SNPs in your bim are in a position of the fasta file where an `N` is found. I'll fix it tonight.

**Comment by endrebak** [comment]
Should be fixed. Try `pip install snpflip==0.0.3` and please reopen if the error persists. Thanks again for reporting this bug.

**Comment by delgrodel** [comment]
Thank you so much for your quick response.  What is odd that I was able to run the program to completion when I used chromosome-specific .bim files.  Hmmm...something to ponder upon.

**Comment by endrebak** [comment]
I made the code more robust, so previous quirks are likely to be gone. If you find otherwise, I'd love to hear about it.
